version: '3'
services:
  admin:
    build: 
      context: ./admin
      dockerfile: ./Dockerfile #path Dockerfile in container
      target: development
    command: npm run start:dev
    env_file:
      - ./admin/.env
    depends_on:
      - db
      - adminer
    volumes:
      - ./admin:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
  # main:
  #   build: 
  #     context: ./main
  #     dockerfile: ./Dockerfile #path Dockerfile in container
  #     target: development
  #   command: npm run start:dev
  #   env_file:
  #     - ./main/.env
  #   depends_on:
  #     - postgres
  #     - adminer
  #   volumes:
  #     - ./main:/usr/src/app/
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3002:3002'

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /var/data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog06021998
  adminer:
   image: adminer
   restart: always
   ports:
    - 8080:8080

      
